"""Add nullable price to Watchlist

Revision ID: 91fd694f3007
Revises: fa6818ed6f22
Create Date: 2025-10-16 10:29:34.575230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fd694f3007'
down_revision: Union[str, Sequence[str], None] = 'fa6818ed6f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'price')
    # ### end Alembic commands ###
