version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity

    volumes:
      - ..:/workspaces:cached
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env.example

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: yfinance_user
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: stocktrackerdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped


volumes:
  pgdata:
